version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"                    # Location of package.json
    schedule:
      interval: "daily"              # You can use "daily" if you want
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
    reviewers:
      - "Qadeer572"                   
