# .readthedocs.yaml
version: 2

# Build documentation in the "docs/" directory using Sphinx or Markdown
sphinx:
  configuration: docs/conf.py   # If you're using Sphinx

# Or if your docs are Markdown files only (no Sphinx):
# mkdocs:
#   configuration: mkdocs.yml

# Define build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

 