version: 2
updates:
  
  - package-ecosystem: "npm"
    directory: "/"                    
    schedule:
      interval: "weekly"              
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "jest"      
        versions: [">=30.0.0"]
    reviewers:
      - "Qadeer572"                   
