name: Deployment Pipeline (Vercel)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optionally install dependencies and build your data scraper
      - name: Build data (optional)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi
          node run.js

      # Trigger Vercel deployment via API (no CLI, no scope issues)
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/${{ secrets.VERCEL_PROJECT_ID }}" \
         
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}'
