name: Documentation Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'source/**'  # only trigger when docs change

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Read the Docs build
        run: |
          curl -X POST -d "" \
          -H "Authorization: Token ${{ secrets.RTD_TOKEN }}" \
          https://readthedocs.org/api/v3/projects/i233059-heavens-above5/builds/
